version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATA_FILE=/home/farzad/data.json
    volumes:
      - ./data:/data/db
      - ./data.json:/home/farzad/data.json
      - ./bash/docker-entrypoint.sh:/home/farzad/docker-entrypoint.sh
#    command: bash -c "bash /home/farzad/docker-entrypoint.sh && tail -f /dev/null"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  mongo:
    driver: bridge